### ISSUE TITLE
`--attrs` Doesn't properly handle escaping commas

### ISSUE THREAD

**Issue by BenB196** [equinix-labs/otel-cli#153]
When making an external web request, You can set [`http.url`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-client) as an attribute to the request. However, the spec states that it should be the full request. The issue is, a URL can look like: `https://example.com?a=b,c=d`. If you were to pass this via `--attrs "http.url=https://example.com?a=b,c=d"`, the values would be split on the comma, resulting in:

`http.url=https://example.com?a=b` & `c=d`

Attempting to escape the comma doesn't seem to work, I tried:

- `--attrs "http.url=https://example.com?a=b\,c=d"`
- `--attrs "http.url=https://example.com?a=b\\,c=d"`
- `--attrs "http.url=https://example.com?a=b\\\,c=d"`

All of which resulted in the value still being split on the comma

**Comment by tobert** [comment]
Thanks for the report! This should be fairly easy to fix. I think that code is using an older hand-written parser and there's already a newer one in otel-cli that uses encoding/csv to parse, and that should do the trick for us. I'm pretty swamped this week but should be able to take care of it early next week.

**Comment by tobert** [comment]
I dug into this while traveling and it looks like it's a documentation bug and not a code bug.

I took one of your examples to create a test and started poking around. Since the `--attrs` flag is parsed by `pflag` via `cobra`, it is already parsed by the Go encoding/csv package and escaping should all work according to CSV rules. I had to go look these up and ended up with this:

https://github.com/equinix-labs/otel-cli/commit/61b537ffcaf3c54cc126daacbbefdc4fe5abd64b

I'll keep working on the branch to patch up a couple places I hand-rolled formatting data and add some notes to the docs so it's clear to expect CSV semantics. I'll add an example too that shows how to escape the CSV in shell so it gets to the command correctly.

**Comment by tobert** [comment]
@BenB196 ^^ can you please give CSV formatting a try in your experiments? I believe it should work with the current release. The trick seems to be that quotes will need escaping so the shell doesn't eat them, and the commas can come through bare e.g. `--attrs item1=value1,\"item2=value2,value3\",item3=value4` or wrap it all in single quotes `--attrs 'item1=value1,"item2=value2,value3",item3=value4'`

**Comment by BenB196** [comment]
Hi @tobert good news, I tested your recommendations and they seem to have worked correctly. Thanks!

**Comment by tobert** [comment]
Hurrah! I'm going to keep this open and tag it as a documentation issue so I don't forget to add CSV examples to the README and elsewhere.

**Comment by tobert** [comment]
With #165 merged there is now a note about escaping attribute values in the README.md.
