### ISSUE TITLE
support timeouts in otel-cli exec

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#55]
When #54 merges, there will be a global timeout flag. As things are, `otel-cli exec` will accept that flag and then ignore it. Even a simple take on timing out the subprocess seems very handy for users.

It perhaps overlaps with the timeout(1) command, but can set status after too so it seems worth it.

**Comment by zerok** [comment]
Hi 🙂  That flag seems to default to 1s which came as a bit of a surprise when I tried `otel-cli exec` on processes that run for a minute or so. Would it perhaps be option to make this flag optional to not enforce a deadline or would it be better to print an error indicating that users should set the timeout appropriately?

Since the timeout is also relevant for sending the span at the end of an exec this error is a bit misleading IMO:

```
2023/09/20 10:11:15 unable to send span: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

The result is (I guess in combination with #258) that if I wrap a command that takes more than the allowed deadline, this error is printed and no root-span is submitted to the endpoint 🙁

**Comment by tobert** [comment]
@zerok gotcha. Yeah that's awkward. The automatic timeout is a leftover from early development when I was worried about otel-cli hanging and messing up peoples' scripts.

I feel that otel-cli should never run without some timeout, so it doesn't end up lingering on machines. So, my inclination is to wrap that error and return better information so you know you need to set a big timeout for your commands.

**Comment by tobert** [comment]
0.4.1 is released and the issue should be solved. Please reopen if the issue persists.
